# Privacy Policy for Auto Download ChatGPT's Voice

Last updated: [Current Date]

## Introduction

This privacy policy explains how our Chrome extension, Auto Download ChatGPT's Voice, collects, uses, and protects your information.

## Information Collection and Use

Our extension collects and stores the following information locally on your device:

1. User Preferences: We store your auto-download setting preference.
2. Download Statistics: We keep track of the total number of downloads and the timestamp of the last download.

This information is stored locally on your device using Chrome's storage API and is not transmitted to any external servers.

## Data Storage

All data collected by our extension is stored locally on your device. We do not transmit, share, or sell any of your personal information.

## Data Access and Control

You can view the stored information by opening the extension's popup interface. To clear this data, you can use Chrome's extension management tools to clear the storage for this extension.

## Changes to Audio Files

Our extension interacts with audio files generated by ChatGPT's text-to-speech feature. It does not modify these files in any way; it simply facilitates their download to your local device.

## Updates to This Policy

We may update this privacy policy from time to time. We will notify you of any changes by posting the new privacy policy on this page.

## Contact Us

If you have any questions about this privacy policy, please contact us at: [Your Contact Email]
